version: '3.7'
services:
  mysql:
    platform: linux/x86_64/v8
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=9mREsvXDs9Gk89E

  postgresql:
    platform: linux/x86_64
    image: postgres:12.10
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  node-app:
    build: node/gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'



